const { test, expect } = require('@playwright/test');
async function login(page, email, password) {
  await page.getByPlaceholder('seu@email.com').fill(email);
  await page.getByPlaceholder('Sua senha').fill(password);
  await page.getByRole('button', { name: 'Entrar no sistema' }).click();
}
test('cadastros, orçamento, transição persistente e portal na API real', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.addInitScript(url => { window.TORQUE_API_URL = url; }, `http://127.0.0.1:${process.env.TORQUE_E2E_API_PORT || 18000}`);
  await page.goto('/');
  await login(page, 'admin@torquegestao.com.br', 'incorreta');
  await expect(page.getByRole('alert')).toContainText('E-mail ou senha inválidos');
  await login(page, 'admin@torquegestao.com.br', 'torque123');
  await expect(page.getByRole('heading', { name: 'Painel do administrador', exact: true })).toBeVisible();
  await expect(page.locator('.summary-tile').filter({ hasText: 'Total de OS' }).locator('strong')).toHaveText('0');
  await expect(page.locator('.summary-tile').filter({ hasText: 'Clientes cadastrados' }).locator('strong')).toHaveText('1');
  await page.getByRole('button', { name: 'Clientes', exact: true }).click();
  await page.getByRole('button', { name: 'Novo cliente' }).click();
  await page.getByLabel('Nome', { exact: true }).fill('Oficina Parceira');
  await page.getByLabel('E-mail', { exact: true }).fill('parceira@example.com');
  await page.getByLabel('CPF / CNPJ').fill('11222333000181');
  await page.getByRole('button', { name: 'Salvar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Oficina Parceira' })).toBeVisible();
  await page.getByRole('button', { name: 'Veículos', exact: true }).click();
  await page.getByRole('button', { name: 'Novo veículo' }).click();
  await page.getByLabel('Cliente', { exact: true }).selectOption({ label: 'Cliente Portal' });
  await page.getByLabel('Placa').fill('ABC1D23');
  await page.getByLabel('Marca').fill('Fiat');
  await page.getByLabel('Modelo').fill('Uno');
  await page.getByRole('button', { name: 'Salvar', exact: true }).click();
  await expect(page.locator('.plate')).toHaveText('ABC1D23');
  await page.getByRole('button', { name: 'Ordens de serviço', exact: true }).click();
  await page.getByRole('button', { name: 'Nova OS', exact: true }).click();
  await page.getByLabel('Cliente', { exact: true }).selectOption({ label: 'Cliente Portal' });
  await page.getByLabel('Veículo', { exact: true }).selectOption({ label: 'ABC1D23 · Fiat Uno' });
  await page.getByLabel('Item do catálogo').selectOption(await page.getByLabel('Item do catálogo').locator('option').filter({ hasText: 'Troca de óleo' }).getAttribute('value'));
  await page.getByRole('button', { name: 'Adicionar', exact: true }).click();
  await page.getByLabel('Item do catálogo').selectOption(await page.getByLabel('Item do catálogo').locator('option').filter({ hasText: 'Filtro de óleo' }).getAttribute('value'));
  await page.getByRole('button', { name: 'Adicionar', exact: true }).click();
  await page.getByLabel('Quantidade de Filtro de óleo').fill('2');
  await page.getByRole('button', { name: 'Emitir ordem de serviço' }).click();
  await expect(page.locator('.total')).toContainText('191,00');
  await page.getByRole('button', { name: 'Avançar para Em Execução' }).click();
  await expect(page.locator('.timeline li')).toHaveCount(2);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Painel do administrador', exact: true })).toBeVisible();
  await expect(page.locator('.summary-tile').filter({ hasText: 'Total de OS' }).locator('strong')).toHaveText('1');
  await expect(page.locator('.summary-tile').filter({ hasText: 'Clientes cadastrados' }).locator('strong')).toHaveText('2');
  await expect(page.locator('.summary-tile').filter({ hasText: 'Veículos cadastrados' }).locator('strong')).toHaveText('1');
  await page.locator('.status-summary').getByRole('button', { name: 'Em Execução 1', exact: true }).click();
  await expect(page.getByLabel('Status', { exact: true })).toHaveValue('em_execucao');
  await expect(page.locator('tbody .badge')).toHaveText('Em Execução');
  await page.getByRole('button', { name: 'Ver detalhes' }).click();
  for (const next of ['Aguardando Peças', 'Finalizada', 'Entregue']) {
    await page.getByRole('button', { name: `Avançar para ${next}`, exact: true }).click();
    await expect(page.locator('.card > p .badge')).toHaveText(next);
  }
  await expect(page.locator('.timeline li')).toHaveCount(5);
  await page.getByRole('button', { name: 'Painel do administrador', exact: true }).click();
  await expect(page.locator('.summary-tile').filter({ hasText: 'Em atendimento' }).locator('strong')).toHaveText('0');
  await expect(page.locator('.status-summary').getByRole('button', { name: 'Entregue 1', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Sair', exact: true }).click();
  await login(page, 'portal@example.com', 'portal123');
  await expect(page.getByRole('heading', { name: 'Meus veículos' })).toBeVisible();
  await expect(page.locator('.plate')).toHaveText('ABC1D23');
  await page.getByRole('button', { name: 'Acompanhar OS', exact: true }).last().click();
  await page.getByRole('button', { name: 'Ver detalhes' }).click();
  await expect(page.locator('.timeline li')).toHaveCount(5);
  await expect(page.getByRole('button', { name: /Avançar para/ })).toHaveCount(0);
  await page.getByRole('button', { name: 'Histórico', exact: true }).click();
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Meus veículos' })).toBeVisible();
  await page.getByRole('button', { name: 'Histórico', exact: true }).first().click();
  await expect(page.locator('tbody .badge')).toHaveText('Entregue');
  await page.evaluate(() => sessionStorage.setItem('torque_access_token', 'expired'));
  await page.getByRole('button', { name: 'Atualizar', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Entrar no sistema' })).toBeVisible();
  expect(errors).toEqual([]);
});
